// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-USPxKL3VpHxd_aBiP1nnivOdNircNc',
    appId: '1:841219069006:android:5190869a1abbb4f2631f1f',
    messagingSenderId: '841219069006',
    projectId: 'influtter-3ddf5',
    storageBucket: 'influtter-3ddf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FPtqO6zh6Fzrnd_ZGOfKNmc7u0mq1Nw',
    appId: '1:841219069006:ios:1d47985e2c577444631f1f',
    messagingSenderId: '841219069006',
    projectId: 'influtter-3ddf5',
    storageBucket: 'influtter-3ddf5.appspot.com',
    iosClientId:
        '841219069006-nmd0g3ht66ubur9bvfh99cl2rdkiv5jm.apps.googleusercontent.com',
    iosBundleId: 'com.liercesantos.oquetemprahoje',
  );
}
